version: '2.0'
services:
  postgres:
    image: postgres:16
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./cocreate-database:/var/lib/postgresql/data