version: '2.0'
services:
  angular:
    build:
      context: cocreate-angular/.
      args:
        port: 4200
    ports:
      - 4200:4200
    depends_on:
      - node
  node:
    build:
      context: cocreate-node/.
      args:
        port: 8000
    ports:
      - 8000:8000