version: '2.0'
services:
  angular:
    build:
      context: cocreate-angular/.
      args:
        port: 4200
    network_mode: host
    depends_on:
      - node
  node:
    build:
      context: cocreate-node/.
      args:
        port: 8000
    network_mode: host
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./cocreate-database:/var/lib/postgresql/data