name: CoCreate Development deploy
on:
  push:
    branches: 
     - 'master'
jobs:
  development-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - run: docker compose down
      - run: docker compose up -d --build
        env:
          NODE_PORT: ${{ secrets.NODE_PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_OAUTH_REDIRECT_URL: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }}
          ORIGIN_URL: ${{ secrets.ORIGIN_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
