name: CoCreate Development deploy
on:
  push:
    branches:
      - 'master'
jobs:
  development-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - run: docker compose down
      - run: |
          docker compose up -d --build \
            -e NODE_PORT=${{ secrets.NODE_PORT }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
            -e SALT_ROUNDS=${{ secrets.SALT_ROUNDS }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e GOOGLE_OAUTH_REDIRECT_URL=${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }} \
            -e ORIGIN_URL=${{ secrets.ORIGIN_URL }}
